Rb 1639
BossaNova/cartographer pull request #4
Opened 2019-08-27 15:10 UTC by SindhuraChayapathy

Want to contribute? Great! Make sure you've read, understood and considered all
the points below before creating your PR:

- Keep your PR under 200 lines of code and address a single concern.
- Add unit test(s) and documentation (these do not count toward your 200 lines).
- Adhere to the [Google C++ Style Guide](https://google.github.io/styleguide/cppguide.html).
- Run `ninja test` or `catkin_make_isolated --install --use-ninja --pkg cartographer --make-args test` as appropriate.
- Keep rebasing (or merging) of master branch to a minimum. It triggers Travis
  runs for every update which blocks merging of other changes. Our merge bot
  will rebase your branch, reformat your source code and merge as the last step
  in the review process.
- Please replace this template text with the commit message you want for your
  PR. You and/or the reviewer should keep it updated during the course of the
  review using the GitHub edit feature.

2019-08-27 21:32 UTC, akshay-prsd requested changes
Some minor requests

2019-08-27 21:32 UTC, akshay-prsd commented on CHANGELOG.rst
> +<<<<<<< 7c531d49368090ee50c84499a299440e1f5af36f
? Rebase problem?

2019-08-27 21:32 UTC, akshay-prsd commented on cartographer/mapping/internal/2d/pose_graph_2d.cc
> +        maybe_add_local_constraint = true;
Both cases set it to true?

2019-08-27 21:32 UTC, akshay-prsd commented on cartographer/mapping/proto/pose_graph_options.proto
> +  bool reduce_global_constraint_search_area = 12;
bool = 12?

2019-08-28 14:04 UTC, schayapathy commented on cartographer/mapping/proto/pose_graph_options.proto
> +  bool reduce_global_constraint_search_area = 12;
Each message type needs to have a unique number associated with it. 
pose_graph_options has 11 messages, adding reduce_global_constraint_search_area as 12th.
https://developers.google.com/protocol-buffers/docs/overview

2019-08-28 14:20 UTC, schayapathy commented on cartographer/mapping/internal/2d/pose_graph_2d.cc
> +        maybe_add_local_constraint = true;
The difference between add_local_constraint and add_global_constraint is the area that is searched to find a constraint.
add_local_constraint calls FastCorrelativeScanMatcher2D::MatchWithSearchParameters() function. 
Here the current pose of the scan is transformed relative to the submap and then optimized within a search area in the submap to find a loop closure constraint.
add_global_constraint calls FastCorrelativeScanMatcher2D::MatchFullSubmap() functions.
Here the current scan pose is randomly initialized at the center of the submap and then the entire submap is searched to find a loop closure constraint.

If you have prior information about the start of a new trajectory then you can add a local_constraint and restrict the search area. It is better because for global search to work the submaps should have a lot of unique features. 
If you are trying to solve robot kidnap problem or any other problem with no prior then it makes sense to add a global_constraint.
 
options_.reduce_global_constraint_search_area() parameter will give us the flexibility to reduce the global search area if we have prior. 
In lines 254 and 255 add_local_constraint and add_global_constraint is set to false.
https://github.com/BossaNova/cartographer/blob/5f63a60bb176de9e3bf10294ff5dd2ca794f0f0e/cartographer/mapping/internal/2d/pose_graph_2d.cc#L254

2019-08-28 14:22 UTC, akshay-prsd commented on cartographer/mapping/proto/pose_graph_options.proto
> +  bool reduce_global_constraint_search_area = 12;
Got it.

2019-08-28 14:53 UTC, akshay-prsd commented
Also can we run the existing tests?

2019-08-28 14:53 UTC, akshay-prsd commented
Also can we run the existing tests?

2019-08-28 16:06 UTC, schayapathy commented
ninja: warning: multiple rules generate abseil/src/abseil-build/absl/synchronization/libabsl_synchronization.a. builds involving this target will not be correct; continuing anyway [-w dupbuild=warn]
[0/1] Running tests...
Test project /home/sindhura/catkin_ws/build_isolated/cartographer/install
      Start  1: cartographer.mapping.2d.range_data_inserter_2d_test
 1/80 Test  #1: cartographer.mapping.2d.range_data_inserter_2d_test .........................................   Passed    0.01 sec
      Start  2: cartographer.mapping.2d.xy_index_test
 2/80 Test  #2: cartographer.mapping.2d.xy_index_test .......................................................   Passed    0.00 sec
      Start  3: cartographer.mapping.2d.map_limits_test
 3/80 Test  #3: cartographer.mapping.2d.map_limits_test .....................................................   Passed    0.00 sec
      Start  4: cartographer.mapping.2d.tsdf_2d_test
 4/80 Test  #4: cartographer.mapping.2d.tsdf_2d_test ........................................................   Passed    0.01 sec
      Start  5: cartographer.mapping.2d.submap_2d_test
 5/80 Test  #5: cartographer.mapping.2d.submap_2d_test ......................................................   Passed    0.01 sec
      Start  6: cartographer.mapping.2d.probability_grid_test
 6/80 Test  #6: cartographer.mapping.2d.probability_grid_test ...............................................   Passed    0.01 sec
      Start  7: cartographer.mapping.2d.tsdf_range_data_inserter_2d_test
 7/80 Test  #7: cartographer.mapping.2d.tsdf_range_data_inserter_2d_test ....................................   Passed    0.02 sec
      Start  8: cartographer.mapping.2d.tsd_value_converter_test
 8/80 Test  #8: cartographer.mapping.2d.tsd_value_converter_test ............................................   Passed    0.01 sec
      Start  9: cartographer.mapping.submaps_test
 9/80 Test  #9: cartographer.mapping.submaps_test ...........................................................   Passed    0.00 sec
      Start 10: cartographer.mapping.3d.submap_3d_test
10/80 Test #10: cartographer.mapping.3d.submap_3d_test ......................................................   Passed    0.00 sec
      Start 11: cartographer.mapping.3d.range_data_inserter_3d_test
11/80 Test #11: cartographer.mapping.3d.range_data_inserter_3d_test .........................................   Passed    0.01 sec
      Start 12: cartographer.mapping.3d.hybrid_grid_test
12/80 Test #12: cartographer.mapping.3d.hybrid_grid_test ....................................................   Passed    0.33 sec
      Start 13: cartographer.mapping.pose_graph_trimmer_test
13/80 Test #13: cartographer.mapping.pose_graph_trimmer_test ................................................   Passed    0.00 sec
      Start 14: cartographer.mapping.map_builder_test
14/80 Test #14: cartographer.mapping.map_builder_test .......................................................   Passed    5.64 sec
      Start 15: cartographer.mapping.pose_graph_test
15/80 Test #15: cartographer.mapping.pose_graph_test ........................................................   Passed    0.01 sec
      Start 16: cartographer.mapping.internal.2d.ray_to_pixel_mask_test
16/80 Test #16: cartographer.mapping.internal.2d.ray_to_pixel_mask_test .....................................   Passed    0.00 sec
      Start 17: cartographer.mapping.internal.2d.normal_estimation_2d_test
17/80 Test #17: cartographer.mapping.internal.2d.normal_estimation_2d_test ..................................   Passed    0.01 sec
      Start 18: cartographer.mapping.internal.2d.pose_graph_2d_test
18/80 Test #18: cartographer.mapping.internal.2d.pose_graph_2d_test .........................................   Passed    0.99 sec
      Start 19: cartographer.mapping.internal.2d.scan_matching.real_time_correlative_scan_matcher_2d_test
19/80 Test #19: cartographer.mapping.internal.2d.scan_matching.real_time_correlative_scan_matcher_2d_test ...   Passed    0.01 sec
      Start 20: cartographer.mapping.internal.2d.scan_matching.correlative_scan_matcher_test
20/80 Test #20: cartographer.mapping.internal.2d.scan_matching.correlative_scan_matcher_test ................   Passed    0.00 sec
      Start 21: cartographer.mapping.internal.2d.scan_matching.ceres_scan_matcher_2d_test
21/80 Test #21: cartographer.mapping.internal.2d.scan_matching.ceres_scan_matcher_2d_test ...................   Passed    0.01 sec
      Start 22: cartographer.mapping.internal.2d.scan_matching.fast_correlative_scan_matcher_2d_test
22/80 Test #22: cartographer.mapping.internal.2d.scan_matching.fast_correlative_scan_matcher_2d_test ........   Passed    3.05 sec
      Start 23: cartographer.mapping.internal.2d.scan_matching.tsdf_match_cost_function_2d_test
23/80 Test #23: cartographer.mapping.internal.2d.scan_matching.tsdf_match_cost_function_2d_test .............   Passed    0.01 sec
      Start 24: cartographer.mapping.internal.2d.scan_matching.occupied_space_cost_function_2d_test
24/80 Test #24: cartographer.mapping.internal.2d.scan_matching.occupied_space_cost_function_2d_test .........   Passed    0.01 sec
      Start 25: cartographer.mapping.internal.2d.scan_matching.interpolated_tsdf_2d_test
25/80 Test #25: cartographer.mapping.internal.2d.scan_matching.interpolated_tsdf_2d_test ....................   Passed    0.01 sec
      Start 26: cartographer.mapping.internal.2d.overlapping_submaps_trimmer_2d_test
26/80 Test #26: cartographer.mapping.internal.2d.overlapping_submaps_trimmer_2d_test ........................   Passed    0.01 sec
      Start 27: cartographer.mapping.internal.connected_components_test
27/80 Test #27: cartographer.mapping.internal.connected_components_test .....................................   Passed    0.01 sec
      Start 28: cartographer.mapping.internal.3d.pose_graph_3d_test
28/80 Test #28: cartographer.mapping.internal.3d.pose_graph_3d_test .........................................   Passed    0.02 sec
      Start 29: cartographer.mapping.internal.3d.local_trajectory_builder_3d_test
29/80 Test #29: cartographer.mapping.internal.3d.local_trajectory_builder_3d_test ...........................   Passed    2.36 sec
      Start 30: cartographer.mapping.internal.3d.scan_matching.ceres_scan_matcher_3d_test
30/80 Test #30: cartographer.mapping.internal.3d.scan_matching.ceres_scan_matcher_3d_test ...................   Passed    0.01 sec
      Start 31: cartographer.mapping.internal.3d.scan_matching.interpolated_grid_test
31/80 Test #31: cartographer.mapping.internal.3d.scan_matching.interpolated_grid_test .......................   Passed    0.02 sec
      Start 32: cartographer.mapping.internal.3d.scan_matching.real_time_correlative_scan_matcher_3d_test
32/80 Test #32: cartographer.mapping.internal.3d.scan_matching.real_time_correlative_scan_matcher_3d_test ...   Passed    0.04 sec
      Start 33: cartographer.mapping.internal.3d.scan_matching.precomputation_grid_3d_test
33/80 Test #33: cartographer.mapping.internal.3d.scan_matching.precomputation_grid_3d_test ..................   Passed    0.02 sec
      Start 34: cartographer.mapping.internal.3d.scan_matching.rotation_delta_cost_functor_3d_test
34/80 Test #34: cartographer.mapping.internal.3d.scan_matching.rotation_delta_cost_functor_3d_test ..........   Passed    0.00 sec
      Start 35: cartographer.mapping.internal.3d.scan_matching.rotational_scan_matcher_test
35/80 Test #35: cartographer.mapping.internal.3d.scan_matching.rotational_scan_matcher_test .................   Passed    0.00 sec
      Start 36: cartographer.mapping.internal.3d.scan_matching.fast_correlative_scan_matcher_3d_test
36/80 Test #36: cartographer.mapping.internal.3d.scan_matching.fast_correlative_scan_matcher_3d_test ........   Passed    1.55 sec
      Start 37: cartographer.mapping.internal.trajectory_connectivity_state_test
37/80 Test #37: cartographer.mapping.internal.trajectory_connectivity_state_test ............................   Passed    0.01 sec
      Start 38: cartographer.m [...]

2019-10-18 16:15 UTC, closed without merging